var RULES = [
    {id:"no-font-family",priority:0,summary:"不允许业务代码设置字体",desc:"由于业务代码中随意设置字体，导致字体取值混乱，因此不允许随意在业务代码中设置字体",checked:true},
    {id:"combine-into-one",priority:1,summary:"将多个子样式合并",desc:"有的子样式可以合并为总样式，包括<code>margin</code> <code>padding</code> <code>font</code> <code>background</code> <code>border</code>等，合并以后可以获得更好的执行效率和压缩效果，<br/>例如：<br/><code>.test {margin:4px; margin-right:0;}</code><br/><code>==></code><br/><code>.test{margin:4px 0 4px 4px}</code><br/>",checked:true},
    {id:"combine-same-rulesets",priority:0,summary:"合并两个完全相同的规则集",desc:"如果两个规则集完全一样，则可以进行合并。<br>需要指出的是：合并可能会带来功能上的问题。如果有问题，还请告知~<br>例如：<br><code>.a {width:100px}</code><br><code>.b {width:100px}</code><br><code>==></code><br><code>.a, .b {width:100px}</code><br><br><strong>安全模式下将不执行此规则</strong><br>",checked:true},
    {id:"comment-length",priority:2,summary:"注释不能超过80个字符",desc:"注释长度不能超过80个字符，40个汉字，如果超出，则应该要换行~",checked:false},
    {id:"css3-with-prefix",priority:2,summary:"CSS3前缀相关检查",desc:"CSS3属性的前缀，有的可以省略，比如：<br><code>border-radius</code><br>有的是省略，必须写全，比如：<br><code>transition</code> <code>transform</code>等<br>在编写顺序上，本工具要求按照<br><code>-webkit-,-moz-,-ms-,-o-,std</code><br>的顺序来编写，并且严格将属性的第一个字符对齐。",checked:false},
    {id:"css3-prop-spaces",priority:2,summary:"CSS3缩进相关检查",desc:"CSS3属性的缩进，必须将属性名称的第一个字符对齐。即：<br><code>-webkit-transition:3s;</code><br><code>&nbsp;&nbsp;&nbsp;-moz-transition:3s;</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;-ms-transition:3s;</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-o-transition:3s;</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;transition:3s;</code>",checked:false},
    {id:"no-style-for-simple-selector",priority:0,summary:"不要为简单选择器设置样式",desc:"一些简单的选择器，比如：<br><code>.nav/.list/.content</code><br>非常容易造成属性的相互覆盖，因此在写这样的选择器时，最好加上前缀，比如<br><code>.module-name .nav</code><br><br>工具现有的简单选择器判断，请参考：<br><code>plugins/helper.py</code>",checked:true},
    {id:"no-style-for-tag",priority:0,summary:"不要为html tag设置样式",desc:"除了重置 CSS(如Reset.css) 的相关设置，其他代码一律不允许为html tag设置样式。",checked:true},
    {id:"outline-zero",priority:1,summary:"修复outline:none",desc:"<code>outline:none</code> 和 <code>outline:0</code> 实现了相同的功能，但是后者的代码更简洁，便于压缩。",checked:true},
    {id:"font-unit",priority:0,summary:"字体的单位必须用px或pt",desc:"字体的单位可以有很多种，比如 <code>px pt em %</code> 等等，为了统一取值，统一要求为 <code>px/pt</code> ， 例如：<br><code>font-size: 12px;</code><br><code>font-size: 14pt;</code>",checked:true},
    {id:"hack-prop",priority:0,summary:"hack属性时的检查",desc:"必须使用正确的 hack 方式， 比如 <code>_ * +</code> 等，其他的属性前缀一律不允许",checked:true},
    {id:"hack-ruleset",priority:0,summary:"hack规则时的检查",desc:"针对Firefox Opera Safari等浏览器的 hack 方式， <strong>人人FED CSS编码规范中有详细的描述， 不允许使用规定之外的方式进行规则级别的hack</strong>",checked:true},
    {id:"hexadecimal-color",priority:1,summary:"16进制颜色大写&缩写",desc:"<p>浏览器会先将小写的颜色值转换成大写，所以写成大写格式可以省略这部分的开销，并且尽量省略，例如：</br><code>color:#ffffff; </code><br/><code>==></code><br/><code>color:#FFF;</code></p>",checked:true},
    {id:"high-perf-selector",priority:0,summary:"针对低性能的选择器的检查",desc:"低性能选择器，害人害己还集体，本工具收集了一些低性能选择器的情形，具体请参见：<br><code>FEDHighPerformanceSelector.py</code>中的相关内容",checked:true},
    {id:"multi-line-brace",priority:2,summary:"多行CSS风格的括号检查",desc:"用于检查多行风格下的 <code>{</code> 和 <code>}</code> 的编写风格，前后空格符和回车符的情况等。",checked:false},
    {id:"multi-line-selector",priority:2,summary:"多行CSS风格的选择器检查",desc:"多行风格下，每一个选择器单独占一行，并以逗号结尾，例如：<br><code>.a,</code><br><code>.b,</code><br><code>.c {</code><br><code>&nbsp;&nbsp;&nbsp;&nbsp;width: 100px;</code><br><code>}</code>",checked:false},
    {id:"multi-line-space",priority:2,summary:"CSS多行风格的空格检查",desc:"多行风格下，CSS的空格检查包括：<ol><li>选择器的空格</li><li>属性的空格</li><li>结尾}的空格</li></ol>具体请参见人人相关的CSS规范",checked:false},
    {id:"add-author",priority:0,summary:"xxx",desc:"xxx",checked:true},
    {id:"no-alpha-image-loader",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"no-appearance-word-in-selector",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"no-comment-in-value",priority:2,summary:"xxx",desc:"xxx",checked:false},
    {id:"no-empty-ruleset",priority:0,summary:"xxx",desc:"xxx",checked:true},
    {id:"no-expression",priority:0,summary:"xxx",desc:"xxx",checked:true},
    {id:"number-in-selector",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"no-star-in-selector",priority:0,summary:"xxx",desc:"xxx",checked:true},
    {id:"del-unit-after-zero",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"no-zero-before-dot",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"remove-duplicated-attr",priority:0,summary:"xxx",desc:"xxx",checked:true},
    {id:"no-border-zero",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"no-underline-in-selector",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"add-semicolon",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"do-not-use-important",priority:0,summary:"xxx",desc:"xxx",checked:true},
    {id:"single-line-brace",priority:2,summary:"xxx",desc:"xxx",checked:false},
    {id:"single-line-selector",priority:2,summary:"xxx",desc:"xxx",checked:false},
    {id:"single-line-space",priority:2,summary:"xxx",desc:"xxx",checked:false},
    {id:"keep-in-order",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"no-chn-font-family",priority:0,summary:"xxx",desc:"xxx",checked:true},
    {id:"unknown-css-prop",priority:0,summary:"xxx",desc:"xxx",checked:true},
    {id:"unknown-html-tag",priority:0,summary:"xxx",desc:"xxx",checked:true},
    {id:"lowercase-prop",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"lowercase-selector",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"single-quotation",priority:1,summary:"xxx",desc:"xxx",checked:true},
    {id:"valid-values",priority:0,summary:"xxx",desc:"xxx",checked:true},
    {id:"z-index-in-range",priority:0,summary:"xxx",desc:"xxx",checked:true}
];